apiVersion: v1
kind: Secret
metadata:
  name: {{ template "node.fullname" . }}
  labels: {{- include "node.labels" . | nindent 4 }}
type: Opaque
data:
{{- if not (empty .Values.externalDatabase) }}
  {{- if not (empty .Values.externalDatabase.host) }}
  DB_HOST: "{{ .Values.externalDatabase.host | b64enc }}"
  {{ else }}
  DB_HOST: {{ required "A DB Host is required!" .Values.externalDatabase.host }}
  {{- end }}
  {{- if not (empty .Values.externalDatabase.port) }}
  DB_PORT: "{{ .Values.externalDatabase.port | b64enc }}"
  {{ else }}
  DB_PORT: "{{ "3306" | b64enc }}"
  {{- end }}
  {{- if not (empty .Values.externalDatabase.user) }}
  DB_USER: "{{ .Values.externalDatabase.user | b64enc }}"
  {{ else }}
  DB_USER: {{ required "A DB User is required!" .Values.externalDatabase.user }}
  {{- end }}
  {{- if not (empty .Values.externalDatabase.password) }}
  DB_PASSWORD: "{{ .Values.externalDatabase.password | b64enc }}"
  {{ else }}
  DB_PASSWORD: {{ required "A DB Root Password is required!" .Values.externalDatabase.password }}
  {{- end }}
  {{- if not (empty .Values.externalDatabase.database) }}
  DB_NAME: "{{ .Values.externalDatabase.database | b64enc }}"
  {{ else }}
  DB_NAME: {{ required "A DB Name is required!" .Values.externalDatabase.database }}
  {{- end }}
{{- end }}

{{- if not (empty .Values.s3Config) }}
  {{- if not (empty .Values.s3Config.bucket) }}
  S3_BUCKET: "{{ .Values.s3Config.bucket | b64enc }}"
  {{ else }}
  S3_BUCKET: {{ required "A DB Name is required!" .Values.s3Config.bucket }}
  {{- end }}
  {{- if not (empty .Values.s3Config.region) }}
  S3_REGION: "{{ .Values.s3Config.region | b64enc }}"
  {{ else }}
  S3_REGION: {{ required "A DB Name is required!" .Values.s3Config.region }}
  {{- end }}
  {{- if not (empty .Values.s3Config.accessKey) }}
  S3_ACCESS: "{{ .Values.s3Config.accessKey | b64enc }}"
  {{- end }}
  {{- if not (empty .Values.s3Config.secretKey) }}
  S3_SECRET: "{{ .Values.s3Config.secretKey | b64enc }}"
  {{- end }}
{{- end }}
