version: '3.5'

volumes:
  postgres-data:
  node_modules:

networks:
  default:
    name: vega-${PROJECT_NAME}

x-app-volumes: &app-volumes
    - ./:/app
    - node_modules:/app/node_modules
    # Add any custom configuration files here

x-app-envsfile: &app-envsfile .env

x-app-networks: &app-networks
  - default

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NODE_VERSION: ${NODE_VERSION}
    image: srijanlabs/node:${NODE_VERSION}-buster-local
    container_name: ${PROJECT_NAME}_backend
    command: ["npm", "start"]
    working_dir: /app
    ports: 
      - ${APPLICATION_PORT}:3000
    depends_on:
      - postgres
    volumes: *app-volumes
    networks: *app-networks
    env_file:  *app-envsfile
  
  postgres:
    image: postgres:12.6-alpine
    container_name: ${PROJECT_NAME}_postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

    networks: *app-networks
    env_file:  *app-envsfile
