# -*- mode: Python -*-

node_version = 12
docker_compose('docker-compose.yml')

docker_build(
  # Image name - must match the image in the docker-compose file
  'srijanlabs/node:' + node_version + '-10-local',
  # Docker context
  '.',
  build_args={'NODE_VERSION': node_version},
  live_update = [
    # Sync local files into the container.
    sync('.', '/app')
  ])
