version: '3.5'

volumes:
  postgres-data:
  node_modules:

networks:
  default:
    name: vega-${PROJECT_NAME}

x-app-volumes: &app-volumes
    - ./:/app
    - node_modules:/app/node_modules
    # Add any custom configuration files here

x-app-envsfile: &app-envsfile .env

x-app-networks: &app-networks
  - default

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NODE_VERSION: ${NODE_VERSION}
    image: srijanlabs/node:${NODE_VERSION}-buster-local
    container_name: ${PROJECT_NAME}_backend
    command: ["npm", "run", "debug"]
    working_dir: /app
    ports: 
      - ${APPLICATION_PORT}:3000
      - 9229:9229
    volumes: *app-volumes
    networks: *app-networks
    env_file:  *app-envsfile