FROM srijanlabs/php-cli:7.3-1.x
COPY composer.json composer.lock /app/
COPY scripts /app/scripts
RUN composer install --no-dev --prefer-dist --no-progress --no-suggest --no-interaction --optimize-autoloader
COPY . /app
